Wrap totalwealth value with USD.parse [ISSUE #7]
ucsb-cs156-f24/proj-happycows-f24-11 pull request #23
Opened 2024-11-20 01:31 UTC by JohnLins

## Overview

In this PR, I used USD.parse() to allow OurTable to properly sort the totalWealth column of the leaderboard table.

## Screenshots (Optional)
![image](https://github.com/user-attachments/assets/b2d66ab8-4ffe-4590-9140-f3a6470587c9)

## Feedback Request (Optional)

Please give suggestions on the following:
- This method might not be the best way to do things. What do you think?
- The way this is implemented is the best I can think of. Is it acceptable?
- Where should these things go? I put them here, but it feels out of place.

## Future Possibilities (Optional)

Some possible points could be:
- This is the beginning/part of (insert feature).
- We can extend this to add (something beyond current functions).
- This can make things easier to (insert project).

## Validation (Optional)

1. Download this branch.
2. Run the project.
3. Go to this page.
4. Test this function.

## Tests

- [ ] Backend Unit tests (`mvn test`) pass
- [ ] Backend Test coverage (`mvn test jacoco:report`) 100%
- [ ] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [ ] Frontend Unit tests (`npm test`) pass
- [ ] Frontend Test coverage (`npm run coverage`) 100%
- [ ] Frontend Mutation tests (`npx stryker run`) 100% 
- [ ] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #0

2024-11-21 00:24 UTC, smmzhu commented on frontend/src/main/components/Leaderboard/LeaderboardTable.js
> +
remove the whitespace

2024-11-21 00:25 UTC, smmzhu commented on .java-version
> -17
why the change?

2024-11-21 00:25 UTC, smmzhu requested changes
Fix comments

2024-11-21 00:48 UTC, smmzhu commented on frontend/src/main/components/Leaderboard/LeaderboardTable.js
> +
remove space

2024-11-21 00:48 UTC, smmzhu commented on frontend/src/main/components/Leaderboard/LeaderboardTable.js
> +
remove space

2024-11-21 00:49 UTC, smmzhu approved these changes
LGTM

2024-11-24 21:51 UTC, pconrad approved these changes
LGTM.  I'd prefer if there were a test, but I've factored that out into a separate issue, #39

2024-11-24 22:14 UTC, merged