Aden courses table
ucsb-cs156-f24/proj-happycows-f24-11 pull request #51
Opened 2024-11-25 21:32 UTC by adenjo6

## Overview

In this PR, I finished Courses Tables. I added CoursesTable.js, CoursesTable.tests.js, coursesUtils.js, and CoursesTable.stories.js

## Screenshots (Optional)
Storybook:
<img width="180" alt="Screenshot 2024-11-25 at 1 30 10 PM" src="https://github.com/user-attachments/asset

Empty Table:
<img width="173" alt="Screenshot 2024-11-25 at 1 30 31 PM" src="https://github.com/user-attachments/assets/6a605389-7769-48ba-8ad2-b8cd3db0f569">
s/34f5bd97-2729-41ef-a2a6-76e55be25530">

Three Items (USER):
<img width="221" alt="Screenshot 2024-11-25 at 1 31 12 PM" src="https://github.com/user-attachments/assets/80966356-35f8-4b38-9c6c-303f492b3dab">

Three Items (ADMIN):

<img width="333" alt="Screenshot 2024-11-25 at 1 31 18 PM" src="https://github.com/user-attachments/assets/8b9eafa2-a092-4485-b1fd-65020fd546a6">

## Tests

- [ ] Backend Unit tests (`mvn test`) pass
- [ ] Backend Test coverage (`mvn test jacoco:report`) 100%
- [ ] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [ ] Frontend Unit tests (`npm test`) pass
- [ ] Frontend Test coverage (`npm run coverage`) 100%
- [ ] Frontend Mutation tests (`npx stryker run`) 100% 
- [ ] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #45

2024-11-25 22:56 UTC, smmzhu submitted a review, later dismissed
lgtm

2024-11-26 01:48 UTC, adenjo6 commented
Note:
I clicked merge instead of rebase, so my previous PR #50 's 16 files show up here. there are only 5 files changed for this specific PR.  I will make sure to rebase whenever possible to avoid clutter.

2024-11-29 18:08 UTC, pconrad requested changes
What is the Join button for that you can see in this [Storybook](https://ucsb-cs156-f24.github.io/proj-happycows-f24-11/prs/51/storybook/?path=/story/components-courses-coursestable--three-items-ordinary-user) and: Screenshot:

<img width="249" alt="image" src="https://github.com/user-attachments/assets/85255d68-349f-456b-82fb-70a4bea7cdd6">

My guess is that this is left over from the Organic code you copied over—but here's the thing: there's no "join" functionality in HappyCows, unlike Organic—no user story that this button connects to, and no backend endpoint that would make sense for it to be connected to.

Always be thinking about what the end user is going to do with the code you are adding!

2024-11-29 18:08 UTC, pconrad commented on frontend/src/main/components/Courses/CoursesTable.js
> +     columns.push(ButtonColumn("Join", "primary", joinCallback, "CoursesTable"));
```suggestion

```

2024-11-29 18:08 UTC, pconrad commented on frontend/src/main/components/Courses/CoursesTable.js
> +    };
What is this 'join' page?   I don't think we have one in this app.  If I'm mistaken, please explain.
```suggestion

```

2024-11-29 18:08 UTC, pconrad commented on frontend/src/tests/components/Courses/CoursesTable.test.js
> +    expect(joinButton).toHaveClass("btn-primary");
```suggestion

```

2024-11-29 18:08 UTC, pconrad commented on frontend/src/tests/components/Courses/CoursesTable.test.js
> +    expect(joinButton).toBeInTheDocument();
```suggestion
 
```

2024-11-30 00:38 UTC, adenjo6 reviewed
Accepted all changes. The join button should be removed as the Courses will be implemented in the commons in the future

2024-11-30 23:02 UTC, merged